# Configuração do container MySQL

version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: ecommerce-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: super_secreta
      MYSQL_DATABASE: ecommerce_db
    ports:
      - "3307:3306"
    volumes:
      - ./db_data:/var/lib/mysql
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
